### ISSUE TITLE
No releases found for ddev-playwright

### ISSUE THREAD

**Issue by rellafella** [deviantintegral/ddev-playwright#5]
We are looking at setting up some integrated Playwright testing into our DDEV workflows so thought we would check out if someone else has already done the heavy lifting, so firstly thank you.

When I tried running `ddev get deviantintegral/ddev-playwright` I was met with "No releases found for ddev-playwright"

Am I doing something wrong or has this been unpublished?

**Comment by deviantintegral** [comment]
I didn't know that releases were required for ddev get to work! I just tagged a 0.1.0 release, and confirmed ddev git now works. Thank you!
