### ISSUE TITLE
report not shown on ddev-host

### ISSUE THREAD

**Issue by nabossha** [deviantintegral/ddev-playwright#6]
i am unable to access the generated html-reports using ` ddev playwright show-report`.
trying to access https://somesite.ddev.site:9324  I get a "`Bad Gateway`" error in my browser - on the other hand accessing KasmVNC works as expected using https://somesite.ddev.site:8444/  

i am only able to access the generated reports by explicitly using the `--host 0.0.0.0` argument:
![image](https://github.com/deviantintegral/ddev-playwright/assets/3851681/4854d2fa-2fa1-431b-bc8e-386586d0a991)

Is this a known limitation to DDEV or Playwright? I have not found a solution using playwright.config.js to set the host for the Reporter by default.

**Comment by deviantintegral** [comment]
It's a known limitation of Playwright unfortunately. There's no way to specify the host parameter for `show-report` from the configuration file. I was pretty sure there was a discussion on this, but I can't find it right now as it appears Playwright has disabled the discussions section: https://github.com/microsoft/playwright/issues/27501#issuecomment-1758077630

You can specify this for `playwright test` though:

```
    return process.env.CI ? [['line'], ['blob']] : [
      [
        'html', {
        // open: 'never',
        host: '0.0.0.0',
        port: 9323,
      }
      ],
      ['list'],
    ];
```

**Comment by nabossha** [comment]
thanks!
