### ISSUE TITLE
Show report Bad Gateway

### ISSUE THREAD

**Issue by tibezh** [deviantintegral/ddev-playwright#8]
Hi there, I have a trouble, with a show report.

Steps to reproduce:

1. Create an empty folder
2. Create index.php file with `<?php phpinfo();` content.
3. Install ddev-playwright according to instructions in the README.md file.
4. Run tests via `ddev playwright test` command.
5. Run show-report via `ddev playwright show-report` command.
6. Check pages with :9324 and :8323 ports.

I have https://test-playwright.ddev.site domain so on https://test-playwright.ddev.site:9324/ and http://test-playwright.ddev.site:8323/ pages I got "Bad Gateway" content with 502 HTTP response status.

**Comment by tibezh** [comment]
Thank you @deviantintegral, it works!

**Comment by yanniboi** [comment]
This is a great solution for `ddev playwright show-report` but I am running `ddev playwright test` and when it errors it has the following option.

```
3 failed
    [chromium] › tests/macallan.test.js:4:5 › has title ────────────────────────────────────────────
    [firefox] › tests/macallan.test.js:4:5 › has title ─────────────────────────────────────────────
    [webkit] › tests/macallan.test.js:4:5 › has title ──────────────────────────────────────────────

  Serving HTML report at http://localhost:9323
```

I still get the `Bad Gateway` error and there is no `host` option for the test command. Any ideas?

**Comment by deviantintegral** [comment]
@yanniboi try setting host and port in your `playwright.config.ts` file. You can now specify the host address to bind too there.

Here's what we have on a project you can edit as needed.

```
  reporter: (() => {
    // The default dot reporter on CI only renders dots when tailing GitHub
    // actions logs when a new line is rendered. This makes it hard to tell if
    // a test has hung. Instead, default to line on CI and html + list
    // everywhere else.
    // https://playwright.dev/docs/test-reporters#reporters-on-ci
    return process.env.CI ? [['line'], ['blob']] : [
      [
        'html', {
        // open: 'never',
        host: '0.0.0.0',
        port: 9323,
      }
      ],
      ['list'],
    ];
  })(),
```

It would be a good idea to put this in the README!
